<div class="slide">
	<div class="left-slide">
		<p id="a"><?php echo $this->__('HOT'); ?></p>
		<p id="b"><?php echo $this->__('SALE'); ?></p>
		<p id="c"><?php echo $this->__('COLLECTION'); ?></p>
		<p id="d"><?php echo $this->__('2013'); ?></p>
		<div class="view">
			<a href="#"><?php echo $this->__('VIEW COLLECTIONS'); ?>&nbsp;<img src="<?php echo $this->getSkinUrl('images/arr.png'); ?>" alt=""/></a>
		</div>
	</div>
	<div class="right-slide">
		<img src="<?php echo $this->getSkinUrl('images/default.png'); ?>">
	</div>
</div>